### ISSUE TITLE
Can you make it larger? :)

### ISSUE THREAD

**Issue by frandroid** [esalter-va/chromescape-navigator#2]
Hi, I've been looking for this for a while, thanks for making it!

It's actually useful for me as in my current Firefox theme, the transparency of the default loading arrow on a tab just blends in the background and makes it invisible.

I'm wondering if there's a way to make it into a two-line icon so I could fit it over two toolbars, or even larger within the current line...  On a 15" macbook pro retina screen it pretty small, and on a 4K screen it pretty much disappears (I mean, so does everything else, but still).

**Comment by evansalter** [comment]
Glad to hear you're enjoying it!

As far as I know there is no way to create an extension with a larger icon. Perhaps there's a setting in Firefox that will adjust the scaling of the toolbar icons, allowing you to make all of them bigger?

Sorry I couldn't help more with this

**Comment by Melonking906** [comment]
Hi just to follow this up, you can make it larger using firefoxs CSS system on your local browser.

First enable userChrome.css in firefox and then add these 2 lines:
`#_99138ee6-534b-402d-b59d-29b29b786867_-browser-action { --toolbarbutton-inner-padding: 0px }
#_99138ee6-534b-402d-b59d-29b29b786867_-browser-action .toolbarbutton-icon{ width: 28px !important; height: 28px !important; margin-left: 5px; }`
